name: ci

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm v7
        run: npm i -g npm@7

      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build'
        run: npm run build --if-present
      - name: 'Lint'
        run: npm run lint --if-present
      - name: 'Test'
        run: npm run test --if-present
      - name: 'Copy files for screen and controller'
        run: |
          cp build/index.html build/screen.html
          cp build/index.html build/controller.html
      - name: 'Deploy'
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build